apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-frontend
  minReplicas: 1
  maxReplicas: 12  # Frontend는 트래픽 변동이 클 수 있음
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60  # Frontend는 더 낮은 임계값
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70