apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  labels:
    app: service-frontend
spec:
  type: ClusterIP
  selector:
    app: service-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP