apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
data:
  init-mongo.js: |
    // MongoDB 초기화 스크립트
    // currency_db 데이터베이스 생성 및 초기 데이터 설정
    
    // admin 데이터베이스에서 사용자 생성 (표준 방식)
    db = db.getSiblingDB('admin');

    // 애플리케이션용 사용자 생성
    db.createUser({
      user: 'trip_user',
      pwd: 'trip-service-mongo',
      roles: [
        {
          role: 'readWrite',
          db: 'currency_db'
        }
      ]
    });

    // 실제 작업할 데이터베이스로 전환
    db = db.getSiblingDB('currency_db');
    
    // 초기 컬렉션 생성
    db.createCollection('country_selections');
    db.createCollection('user_rankings');
    db.createCollection('click_logs');
    
    // 인덱스 생성
    db.country_selections.createIndex({ "country_code": 1 });
    db.country_selections.createIndex({ "timestamp": -1 });
    db.user_rankings.createIndex({ "country_code": 1 });
    db.user_rankings.createIndex({ "click_count": -1 });
    db.click_logs.createIndex({ "timestamp": -1 });
    db.click_logs.createIndex({ "country_code": 1 });
    
    // 초기 샘플 데이터 삽입
    db.country_selections.insertMany([
      {
        country_code: "US",
        country_name: "미국",
        currency_code: "USD",
        click_count: 0,
        last_updated: new Date()
      },
      {
        country_code: "JP",
        country_name: "일본",
        currency_code: "JPY",
        click_count: 0,
        last_updated: new Date()
      },
      {
        country_code: "EU",
        country_name: "유럽연합",
        currency_code: "EUR",
        click_count: 0,
        last_updated: new Date()
      },
      {
        country_code: "GB",
        country_name: "영국",
        currency_code: "GBP",
        click_count: 0,
        last_updated: new Date()
      },
      {
        country_code: "CN",
        country_name: "중국",
        currency_code: "CNY",
        click_count: 0,
        last_updated: new Date()
      }
    ]);
    
    print('MongoDB 초기화 완료: currency_db 데이터베이스 및 초기 데이터 설정됨');