apiVersion: v1
kind: Service
metadata:
  name: service-history
  labels:
    app: service-history
spec:
  type: ClusterIP
  selector:
    app: service-history
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP