apiVersion: v1
kind: Service
metadata:
  name: service-history
spec:
  selector:
    app: service-history
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30003
  type: NodePort