apiVersion: v1
kind: Service
metadata:
  name: service-currency
spec:
  selector:
    app: service-currency
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30001
  type: NodePort